"""initial_schema

Revision ID: 4e7709c2bfad
Revises: 
Create Date: 2026-08-30 10:39:25.241511
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e7709c2bfad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customers_created_at', 'customers', ['created_at'], unique=False)
    op.create_table('merchants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_code', sa.String(length=10), nullable=True),
    sa.Column('risk_level', sa.String(length=10), server_default='LOW', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("risk_level IN ('LOW', 'MEDIUM', 'HIGH')", name='ck_merchants_risk_level'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_merchants_category_code', 'merchants', ['category_code'], unique=False)
    op.create_index('ix_merchants_name', 'merchants', ['name'], unique=False)
    op.create_table('risk_rules_config',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('score_contribution', sa.Integer(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score_contribution >= 0 AND score_contribution <= 100', name='ck_risk_rules_config_score'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_name', name='uq_risk_rules_config_rule_name')
    )
    op.create_index('ix_risk_rules_config_rule_name', 'risk_rules_config', ['rule_name'], unique=True)
    op.create_table('customer_devices',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint("device_type IN ('mobile', 'desktop', 'pos')", name='ck_customer_devices_device_type'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'device_fingerprint', name='uq_customer_devices_customer_fingerprint')
    )
    op.create_index('ix_customer_devices_customer_id', 'customer_devices', ['customer_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='customer', nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('customer', 'fraud_analyst', 'admin')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_customer_id', 'users', ['customer_id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=50), nullable=True),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_actor_id', 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_table('model_metadata',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('artifact_path', sa.String(length=500), nullable=False),
    sa.Column('training_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feature_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('trained_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['trained_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_version', name='uq_model_metadata_model_version')
    )
    op.create_index('ix_model_metadata_version', 'model_metadata', ['model_version'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('location_country', sa.String(length=100), nullable=True),
    sa.Column('location_city', sa.String(length=100), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=10), nullable=True),
    sa.Column('decision', sa.String(length=10), nullable=True),
    sa.Column('ml_score', sa.Integer(), nullable=True),
    sa.Column('behaviour_score', sa.Integer(), nullable=True),
    sa.Column('rule_score', sa.Integer(), nullable=True),
    sa.Column('explanation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IN ('APPROVE', 'VERIFY', 'HOLD')", name='ck_transactions_decision'),
    sa.CheckConstraint("device_type IN ('mobile', 'desktop', 'pos')", name='ck_transactions_device_type'),
    sa.CheckConstraint("risk_level IN ('LOW', 'MEDIUM', 'HIGH')", name='ck_transactions_risk_level'),
    sa.CheckConstraint("status IN ('PENDING', 'COMPLETED', 'FAILED')", name='ck_transactions_status'),
    sa.CheckConstraint("transaction_type IN ('purchase', 'transfer', 'withdrawal')", name='ck_transactions_transaction_type'),
    sa.CheckConstraint('LENGTH(currency) = 3', name='ck_transactions_currency'),
    sa.CheckConstraint('amount > 0', name='ck_transactions_amount'),
    sa.CheckConstraint('behaviour_score >= 0 AND behaviour_score <= 100', name='ck_transactions_behaviour_score'),
    sa.CheckConstraint('ml_score >= 0 AND ml_score <= 100', name='ck_transactions_ml_score'),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 100', name='ck_transactions_risk_score'),
    sa.CheckConstraint('rule_score >= 0 AND rule_score <= 100', name='ck_transactions_rule_score'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_version'], ['model_metadata.model_version'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_customer_id', 'transactions', ['customer_id'], unique=False)
    op.create_index('ix_transactions_merchant_id', 'transactions', ['merchant_id'], unique=False)
    op.create_index('ix_transactions_model_version', 'transactions', ['model_version'], unique=False)
    op.create_index('ix_transactions_risk_level', 'transactions', ['risk_level'], unique=False)
    op.create_index('ix_transactions_status', 'transactions', ['status'], unique=False)
    op.create_index('ix_transactions_timestamp', 'transactions', ['timestamp'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=10), server_default='HIGH', nullable=False),
    sa.Column('decision', sa.String(length=10), server_default='HOLD', nullable=False),
    sa.Column('explanation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analyst_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='OPEN', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("decision IN ('APPROVE', 'VERIFY', 'HOLD')", name='ck_alerts_decision'),
    sa.CheckConstraint("risk_level IN ('LOW', 'MEDIUM', 'HIGH')", name='ck_alerts_risk_level'),
    sa.CheckConstraint("status IN ('OPEN', 'IN_REVIEW', 'RESOLVED', 'DISMISSED')", name='ck_alerts_status'),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 100', name='ck_alerts_risk_score'),
    sa.ForeignKeyConstraint(['analyst_id'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_analyst_id', 'alerts', ['analyst_id'], unique=False)
    op.create_index('ix_alerts_status', 'alerts', ['status'], unique=False)
    op.create_index('ix_alerts_transaction_id', 'alerts', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_transaction_id', table_name='alerts')
    op.drop_index('ix_alerts_status', table_name='alerts')
    op.drop_index('ix_alerts_analyst_id', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_transactions_timestamp', table_name='transactions')
    op.drop_index('ix_transactions_status', table_name='transactions')
    op.drop_index('ix_transactions_risk_level', table_name='transactions')
    op.drop_index('ix_transactions_model_version', table_name='transactions')
    op.drop_index('ix_transactions_merchant_id', table_name='transactions')
    op.drop_index('ix_transactions_customer_id', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_model_metadata_version', table_name='model_metadata')
    op.drop_table('model_metadata')
    op.drop_index('ix_audit_logs_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_customer_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_customer_devices_customer_id', table_name='customer_devices')
    op.drop_table('customer_devices')
    op.drop_index('ix_risk_rules_config_rule_name', table_name='risk_rules_config')
    op.drop_table('risk_rules_config')
    op.drop_index('ix_merchants_name', table_name='merchants')
    op.drop_index('ix_merchants_category_code', table_name='merchants')
    op.drop_table('merchants')
    op.drop_index('ix_customers_created_at', table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
